config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get    '/contact', to: 'home#contact'
  get    '/about',   to: 'home#about'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/search',  to: 'searches#show'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :searches
  before_save {self.email = self.email.downcase}
  validates :name, presence: true, length: {maximum: 50}

  #This helper validates that the attribute's value is unique right before the object gets saved.
  #It does not create a uniqueness constraint in the database, so it may happen that two different database connections
  #create two records with the same value for a column that you intend to be unique.
  #To avoid that, you must create a unique index on that column in your database.
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  # from rails docs
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}

  # api.rubyonrails.org - If password confirmation validation is not needed, simply leave out the value
  # for password_confirmation (i.e. don't provide a form field for it). When this attribute has a nil value,
  # the validation will not be triggered.
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contact
  end

  def about    
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  include SearchesHelper

  def show
    if params[:search_term].blank?
      render 'show'
    else
      search_query = params[:search_term].downcase
      get_artistInfo(search_query)
      if logged_in?
        user = User.find(session[:user_id])
        search_entry = user.searches.create({search_query: params[:search_term]})
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if !@user.searches.blank?
      @user_searches = @user.searches.order('created_at DESC').group_by { |c| c.created_at.to_date }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Last.fm Recommendation Engine!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
  BASE_URL = "http://ws.audioscrobbler.com/2.0/?method="
  API_METHODS = ["artist.getinfo", "artist.getTopTracks"]
  API_KEY = "5345e29b04545726f5be7dae7acb9032"
  JSON_FORMAT = "&format=json"

  def get_artistInfo(search_query)
    @artist = Hash.new

    api_parameters = {artist: search_query, api_key: API_KEY}
    info_response = HTTParty.get(BASE_URL + API_METHODS[0] + JSON_FORMAT, query: api_parameters)
    info_response = JSON.parse(info_response.body, symbolize_names: true)
    api_parameters[:limit] = 10
    track_response = HTTParty.get(BASE_URL + API_METHODS[1] + JSON_FORMAT, query: api_parameters)
    track_response = JSON.parse(track_response.body, symbolize_names: true)

    # If any of the responses contains an error,
    if info_response[:error]
      @artist[:error] = info_response[:error]
      @artist[:message] = info_response[:message]
      return
    end
    if track_response[:error]
      @artist[:error] = track_response[:error]
      @artist[:message] = track_response[:message]
      return
    end

    @artist[:name] = info_response[:artist][:name]
    @artist[:url] = info_response[:artist][:url]
    @artist[:bio] = info_response[:artist][:bio][:summary]
    @artist[:similar] = []
    info_response[:artist][:similar][:artist].each do |similar_artist|
      @artist[:similar].push({name: similar_artist[:name], url: similar_artist[:url]})
    end
    @artist[:tracks] = []
    track_response[:toptracks][:track].each do |track|
      @artist[:tracks].push({name: track[:name], url: track[:url]})
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    #this session is a rails method, different from the Sessions controller generated
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
 def current_user
   if session[:user_id]
     #Common ruby idiom
     @current_user ||= User.find_by(id: session[:user_id])
   end
 end

 # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar img-circle")
  end
end

app/views/home/about.html.erb
<p>A recommendation engine which gets you tracks and similar artists from Last.fm corresponding to your searched artist</p>

app/views/home/contact.html.erb
<p>Email: solankipinank10@gmail.com</p>

app/views/home/index.html.erb
<div class="center jumbotron">
  <h2>Welcome to Last.fm Recommendation Engine</h2>
  <%= render 'layouts/search' %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Last.fm Recommendation Engine
    by Pinank Solanki
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <%= link_to "Home", root_path, id: "logo" %>
      <nav>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><%= link_to "#{image_tag('last-fm-logo.png', size: '60x12')}".html_safe,
                        "https://www.last.fm/home"%></li> -->
        <% if logged_in? %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_search.html.erb
<%= form_tag(search_path, method: :get, role: 'form') do %>
  <div class="input-group">
    <%= search_field_tag :search_term, params[:search_term], placeholder: "Search artist here", class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
    </div>
  </div>
  <% if !logged_in? %>
    <small class="form-text text-muted">Log in to record your search queries.</small>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LastFmRecommendationEngine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/searches/show.html.erb
<div class="center jumbotron">
  <%= render 'layouts/search' %>
</div>

<% if params[:search_term].blank? %>

  <div class="alert alert-danger" role="alert">
    Error: Empty field!
  </div>

<% elsif @artist[:error] %>

  <div class="alert alert-danger" role="alert">
    Error: <%= @artist[:message] %>
  </div>

<% else %>

  <div class="container">
    <h1><%= link_to @artist[:name], @artist[:url] %></h1>
  </div>

  <div class="container search-results">
    <div>
      <h2> Biography </h2>
      <p><%= (@artist[:bio].html_safe) %></p>
    </div>

    <div>
      <h2>Top tracks</h2>
      <div class="list-group">
        <ol>
          <% @artist[:tracks].each do |item| %>
            <li><%= link_to item[:name], item[:url], class: "list-group-item" %></li>
          <% end %>
        </ol>
      </div>
    </div>

    <div>
      <h2>Similar Artists</h2>
      <div class="list-group">
        <ul class="list-inline">
          <% @artist[:similar].each do |item| %>
            <li><%= link_to item[:name], item[:url], class: "list-group-item" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<br><br>

<div class="container-fluid well span6">
  <div class="row-fluid">
    <div class="span2" >
      <%= gravatar_for @user %>
    </div>

    <div class="span8">
      <h3><%= @user.name %></h3>
      <h5 class="glyphicon glyphicon-envelope"> <%= @user.email %></h5>
    </div>
  </div>

  <br>
  <hr>

  <% if @user.searches.blank? %>

    <div class="alert alert-info" role="alert">
	    Info! Search something to display your search history here.
    </div>

  <% else %>

    <div class="container mt-5 mb-5">
	    <div class="row">
		    <div class="col-md-6 offset-md-3">
			    <h3 style="margin-top: -2px;">Search history</h3>
			    <ul class="timeline">
            <% @user_searches.each do |date, value| %>
				      <li>
					      <h4 class="float-right"><%= date %></h4>
                <table class="table table-dark">
                  <tbody>
                    <% value.each do |item| %>
                      <tr>
                        <td><%= item.created_at.strftime("%I:%M %p") %></td>
                        <td><%= item.search_query %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
				      </li>
            <% end %>
			    </ul>
		   </div>
	    </div>
    </div>
  <% end %>
</div>